name: Generate default_config.zip

on:
 push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate Artifact
      run : ./scripts/package.sh
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: default_config
        path: target/*