name: Validate PR

on:
 pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate Artifact
      run : ./scripts/package.sh